/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inaitarerep;

/**
 *
 * @author tiani
 */

import java.util.Collections;
import java.awt.Component;

import javax.swing.JOptionPane;
public class Epossimple extends javax.swing.JFrame {

    //global variables to hold single customer sales 
    static double totalOrderCost=0; 
    static double TotalSales=0; //total of all sales
    static int checkoutCount=0;//total number of customers served
    //global arraylist to hold all the customer sales totals. 
    static java.util.ArrayList<Double> salesCollection = new java.util.ArrayList<Double>(); 
    private final static String newline = "\n";
 

    /**
     * Creates new form Epossimple
     */
    public Epossimple() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPaneCheckout = new javax.swing.JOptionPane();
        jOptionPaneOutput = new javax.swing.JOptionPane();
        tabMain = new javax.swing.JTabbedPane();
        pnlOrder = new javax.swing.JPanel();
        lblQuantity = new javax.swing.JLabel();
        cboQuantity = new javax.swing.JComboBox<>();
        lblProductPrice = new javax.swing.JLabel();
        cboProductPrice = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnCheckout = new javax.swing.JButton();
        lblCart = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaList = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        pnlReport = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaReport = new javax.swing.JTextArea();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple EPOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblQuantity.setText("Quantity");

        cboQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboQuantityActionPerformed(evt);
            }
        });

        lblProductPrice.setText("Product : Price");

        btnAdd.setText("ADD TO SHOPLIST");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCheckout.setText("CHECKOUT");
        btnCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckoutActionPerformed(evt);
            }
        });

        lblCart.setText("Shopping Cart");

        txtAreaList.setColumns(20);
        txtAreaList.setRows(5);
        jScrollPane1.setViewportView(txtAreaList);

        btnCancel.setText("CANCEL ORDER");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblTotal.setText("Total : ");

        javax.swing.GroupLayout pnlOrderLayout = new javax.swing.GroupLayout(pnlOrder);
        pnlOrder.setLayout(pnlOrderLayout);
        pnlOrderLayout.setHorizontalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboQuantity, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(lblCart, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOrderLayout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(135, 135, 135))
                            .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOrderLayout.setVerticalGroup(
            pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(lblCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(20, 20, 20)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(btnCheckout))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTotal)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        tabMain.addTab("ORDER", pnlOrder);

        txtAreaReport.setColumns(20);
        txtAreaReport.setRows(5);
        jScrollPane2.setViewportView(txtAreaReport);

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReportLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        tabMain.addTab("REPORT", pnlReport);

        btnExit.setText("EXIT");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(tabMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cboQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboQuantityActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System. exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
       
        txtAreaList.setText("");
        lblTotal.setText("Total: ");
        totalOrderCost=0;
    }//GEN-LAST:event_btnCancelActionPerformed
    
   
    public boolean confirmOrder(){
        boolean bool=false; // initialise bool- used as a return to show if checout was successful ro not
        if(totalOrderCost!=0){
        
         int userInteraction = jOptionPaneCheckout.showConfirmDialog(null, "Total cost of items is : £"+totalOrderCost, "Checkout",  
                JOptionPane.OK_CANCEL_OPTION, 
                JOptionPane.PLAIN_MESSAGE); 

         if (userInteraction == JOptionPane.OK_OPTION)  
         { 
               bool=true;       
         } 
        else 
                 {//user clicked on CANCEL or the X close button- we change the userInteraction  
                    userInteraction = JOptionPane.CANCEL_OPTION; 
                } 
         if ( (userInteraction == JOptionPane.CANCEL_OPTION) || (userInteraction == JOptionPane.CLOSED_OPTION) ) 
            // the cancel block of code - if user presses the X or CANCEL 
                { 
                   bool=false;
                }
         }
         return bool;
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String QuantityOutput=String.valueOf(cboQuantity.getSelectedItem());
        int Quantity= Integer.valueOf(QuantityOutput);// get the item for calculating the total
        String ProdPrice =String.valueOf(cboProductPrice.getSelectedItem()); //extract the price:profuct from combo box
        int colonPlace=ProdPrice.indexOf(":"); //find the position of :
        String Fruit = ProdPrice.substring(0, colonPlace-1); //extract the name of the fruit to display
        String Price= ProdPrice.substring(colonPlace+1); //extract the price to display
        
        Double Price2=Double.valueOf(Price.substring(2)); // remove the pound symbol and turn to float to calculate total
        
        
        txtAreaList.append(QuantityOutput+" x"+"  "+Fruit+"   "+Price+newline);// display details in the text area
       
        totalOrderCost=totalOrderCost+(Price2*Quantity);
        lblTotal.setText("Total: "+totalOrderCost);
       
        
       
    }//GEN-LAST:event_btnAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        for (int x=1;x<11;x++){ //code to fill the combo boxes
          String i= Integer.toString(x);
          cboQuantity.addItem(i);  
         
          
         
    } 
          cboProductPrice.addItem("Melon : £1.15");
          cboProductPrice.addItem("Orange : £0.50");
          cboProductPrice.addItem("Lime: £0.20");
          cboProductPrice.addItem("Kiwi: £0.60");
          cboProductPrice.addItem("Mango : £0.90");
          cboProductPrice.addItem("Banana : £0.85");
           
    txtAreaReport.setText("Total Sales:\nAverage:\nMin:\nMax:\nTotal Customers Served:");
        
    }//GEN-LAST:event_formWindowOpened

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
       //calculations for report
       
       boolean state=confirmOrder();
       if (state==true){
           if (totalOrderCost!=0){
            salesCollection.add(totalOrderCost);
             checkoutCount=checkoutCount+1;
       TotalSales= TotalSales+ totalOrderCost;
       double Average=TotalSales/checkoutCount;
       double Min=  Collections.min(salesCollection);
       double Max=  Collections.min(salesCollection);
       txtAreaReport.setText("Total Sales:"+TotalSales+"\nAverage:"+Average+"\nMin:"+Min+"\nMax:"+Max+"\nTotal Customers Served:"+checkoutCount);  
       txtAreaList.setText("");
       lblTotal.setText("Total: ");
       totalOrderCost=0;  
           }
          
       }else{
         jOptionPaneOutput.showMessageDialog(this,"Your checkout was unsuccessful");
       }
      
       
       
    }//GEN-LAST:event_btnCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Epossimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Epossimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Epossimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Epossimple.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Epossimple().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JButton btnExit;
    private javax.swing.JComboBox<String> cboProductPrice;
    private javax.swing.JComboBox<String> cboQuantity;
    private javax.swing.JOptionPane jOptionPaneCheckout;
    private javax.swing.JOptionPane jOptionPaneOutput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCart;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlOrder;
    private javax.swing.JPanel pnlReport;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextArea txtAreaList;
    private javax.swing.JTextArea txtAreaReport;
    // End of variables declaration//GEN-END:variables
}
